default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: ODPJ_development

test:
  <<: *default
  database: ODPJ_test

production:
  <<: *default
  database: ODPJ_production
